import { DealershipData } from '@/types/dealership';

export const initialDealershipData: DealershipData = {
  dealerInfo: {
    brandName: 'XPENG Motors Indonesia',
    dealershipName: 'XPENG Authorized Central Dealership',
    salesName: 'Hendra Gunawan',
    salesTitle: 'Senior Certified EV Specialist & XPENG Product Consultant',
    salesBadge: 'Top Sales Consultant 2024 & EV Master Certified',
    salesBio: 'Siap melayani konsultasi pembelian XPENG, promo diskon terbaik, simulasi kredit DP ringan / bunga 0%, pengajuan test drive ke rumah/kantor, trade-in semua merk, dan instalasi Wallbox Charger resmi di rumah Anda.',
    salesAvatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80',
    salesIdNumber: 'XP-ID-88902',
    socials: {
      whatsapp: '6281288990022',
      whatsappDisplay: '+62 812-8899-0022',
      instagram: '@xpeng.sales.official',
      instagramUrl: 'https://instagram.com',
      tiktok: '@xpeng.ev.hendra',
      tiktokUrl: 'https://tiktok.com',
      telegram: '@xpeng_hendra_sales',
      telegramUrl: 'https://t.me',
      phone: '+6281288990022',
      phoneDisplay: '0812-8899-0022',
      email: 'hendra.xpeng@dealersales.id',
    },
    whatsappDefaultText: 'Halo Pak Hendra, saya tertarik dengan unit XPENG. Boleh minta info promo & simulasi kredit terbaru?',
    address: 'Jl. Boulevard Artha Gading No. 88, Kelapa Gading Barat, Jakarta Utara, DKI Jakarta 14240',
    city: 'Jakarta Utara',
    operatingHours: 'Senin - Minggu: 08:30 - 20:00 WIB (Showroom & Test Drive)',
    googleMapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.8920430635467!2d106.89066667586524!3d-6.145203360241088!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f56a5e1cf0d7%3A0x7d6a52fa5b7b9195!2sMall%20Artha%20Gading!5e0!3m2!1sen!2sid!4v1700000000000!5m2!1sen!2sid',
    googleMapsLink: 'https://maps.google.com/?q=Mall+Artha+Gading+Jakarta',
    emergencyHotline: '1500-880 (24/7 Roadside Assistance)',
    announcementTicker: '⚡ PROMO BULAN INI: Free Wallbox Charger 7kW + Garansi Baterai 8 Tahun / 160.000 KM + Bunga 0% s/d 2 Tahun + Free Asuransi All Risk!',
    bookingFeeAccount: {
      bankName: 'BCA (Bank Central Asia)',
      accountNumber: '522-039-8899',
      accountHolder: 'PT XPENG MOBIL INDONESIA',
      note: 'Transfer hanya ke rekening resmi dealer atas nama PT. Jangan pernah transfer ke rekening pribadi.',
    },
  },

  heroSlides: [
    {
      id: 'slide-1',
      badge: 'FLAGSHIP ELECTRIC COUPE SUV',
      title: 'XPENG G6 Ultra Smart Coupe SUV',
      subtitle: 'Platform 800V SEPA 2.0 tercepat di kelasnya. Jarak tempuh hingga 570 KM, charging 10-80% hanya dalam 15 menit.',
      priceStart: 'Rp 699.000.000',
      range: '570 km',
      acceleration: '3.9 detik',
      bgImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1920&q=85',
      ctaText: 'Lihat Detail G6',
      ctaLink: '/models/xpeng-g6',
      modelSlug: 'xpeng-g6',
    },
    {
      id: 'slide-2',
      badge: 'LUXURY 7-SEATER SMART MPV',
      title: 'XPENG X9 Ultra Smart MPV',
      subtitle: 'MPV listrik termewah dengan Rear-Wheel Steering aktif, Zero Gravity Seats, dan layar bioskop plafon 21.4 inci.',
      priceStart: 'Rp 1.150.000.000',
      range: '702 km',
      acceleration: '5.7 detik',
      bgImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1920&q=85',
      ctaText: 'Lihat Detail X9',
      ctaLink: '/models/xpeng-x9',
      modelSlug: 'xpeng-x9',
    },
    {
      id: 'slide-3',
      badge: 'FLAGSHIP PERFORMANCE SUV',
      title: 'XPENG G9 Flagship Smart SUV',
      subtitle: 'Kemewahan tanpa kompromi. Suspensi udara dual-chamber, audio Dynaudio 28 speaker, dan XNGP Intelligent Driving.',
      priceStart: 'Rp 1.050.000.000',
      range: '650 km',
      acceleration: '3.9 detik',
      bgImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1920&q=85',
      ctaText: 'Lihat Detail G9',
      ctaLink: '/models/xpeng-g9',
      modelSlug: 'xpeng-g9',
    },
  ],

  models: [
    {
      id: 'model-g6',
      slug: 'xpeng-g6',
      name: 'XPENG G6',
      tagline: 'Ultra Smart Coupe SUV - Next-Gen Intelligence',
      category: 'SUV',
      startingPrice: 699000000,
      formattedPrice: 'Rp 699.000.000',
      rangeKm: '570 KM (WLTP/CLTC)',
      acceleration0to100: '3.9 Detik',
      maxPower: '476 HP / 660 Nm (Performance AWD)',
      batteryCapacity: '87.5 kWh Liquid-cooled LFP/NMC',
      fastChargeTime: '10-80% dalam 15 menit (Supercharging 800V)',
      driveType: 'RWD / Performance AWD',
      heroImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=85',
      sideImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85',
      interiorImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85',
      rearImage: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=85',
      gallery: [
        'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=85',
        'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85',
        'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=85',
      ],
      colors: [
        { name: 'Silver Frost', hex: '#cfd4dc' },
        { name: 'Arctic White', hex: '#f8fafc' },
        { name: 'Midnight Black', hex: '#18181b' },
        { name: 'Photon Orange', hex: '#ea580c' },
        { name: 'Nebula Green', hex: '#0f766e' },
      ],
      variants: [
        {
          name: 'G6 Standard Range RWD',
          price: 699000000,
          formattedPrice: 'Rp 699.000.000',
          range: '435 km',
          acceleration: '6.6 detik',
          drivetrain: 'RWD 258 HP',
          battery: '66 kWh LFP',
        },
        {
          name: 'G6 Long Range RWD',
          price: 779000000,
          formattedPrice: 'Rp 779.000.000',
          range: '570 km',
          acceleration: '6.2 detik',
          drivetrain: 'RWD 286 HP',
          battery: '87.5 kWh NMC',
        },
        {
          name: 'G6 Performance AWD',
          price: 849000000,
          formattedPrice: 'Rp 849.000.000',
          range: '550 km',
          acceleration: '3.9 detik',
          drivetrain: 'Dual Motor AWD 476 HP',
          battery: '87.5 kWh NMC',
        },
      ],
      highlights: [
        'Arsitektur 800V Silicon Carbide SEPA 2.0',
        'XNGP Full-Scenario ADAS dengan 31 Sensor & Dual Orin-X Chip',
        'Panoramic Sunroof dengan teknologi anti UV & Heat Rejection 99.9%',
        'Xmart OS 5.0 dengan layar 14.96 inci & Qualcomm Snapdragon 8155',
        'Wireless Phone Fast Charging 50W dengan sistem pendingin aktif',
        'Garansi Baterai 8 Tahun / 160.000 KM & Free Maintenance 5 Tahun',
      ],
      description: 'XPENG G6 adalah SUV Coupe pintar bertenaga listrik murni yang dirancang untuk mereka yang mengutamakan teknologi, akselerasi instan, dan kenyamanan perjalanan jarak jauh dengan arsitektur charging 800V super cepat.',
      isFeatured: true,
      isHot: true,
      isNew: true,
      inStock: true,
    },
    {
      id: 'model-x9',
      slug: 'xpeng-x9',
      name: 'XPENG X9',
      tagline: 'Ultra Smart 7-Seater Luxury Flagship MPV',
      category: 'MPV',
      startingPrice: 1150000000,
      formattedPrice: 'Rp 1.150.000.000',
      rangeKm: '702 KM (CLTC)',
      acceleration0to100: '5.7 Detik',
      maxPower: '496 HP / 640 Nm (Dual Motor AWD)',
      batteryCapacity: '101.5 kWh 800V Battery',
      fastChargeTime: '10-80% dalam 16 menit (Supercharging 800V)',
      driveType: 'RWD / Performance AWD',
      heroImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=85',
      sideImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85',
      interiorImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85',
      rearImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85',
      gallery: [
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=85',
        'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85',
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85',
      ],
      colors: [
        { name: 'Cosmic Gold', hex: '#c5a059' },
        { name: 'Galaxy Silver', hex: '#94a3b8' },
        { name: 'Dark Knight', hex: '#0f172a' },
        { name: 'Crystal White', hex: '#f1f5f9' },
      ],
      variants: [
        {
          name: 'X9 610 Pro RWD',
          price: 1150000000,
          formattedPrice: 'Rp 1.150.000.000',
          range: '610 km',
          acceleration: '7.7 detik',
          drivetrain: 'RWD 315 HP',
          battery: '84.5 kWh LFP',
        },
        {
          name: 'X9 702 Max Long Range',
          price: 1250000000,
          formattedPrice: 'Rp 1.250.000.000',
          range: '702 km',
          acceleration: '7.7 detik',
          drivetrain: 'RWD 315 HP',
          battery: '101.5 kWh NMC',
        },
        {
          name: 'X9 640 Performance AWD Max',
          price: 1380000000,
          formattedPrice: 'Rp 1.380.000.000',
          range: '640 km',
          acceleration: '5.7 detik',
          drivetrain: 'Dual Motor AWD 496 HP',
          battery: '101.5 kWh NMC',
        },
      ],
      highlights: [
        'Active Rear-Wheel Steering (Radius Putar Hanya 5.4m seperti sedan kecil)',
        'Kursi Baris Kedua Zero-Gravity dengan Massage 10-titik & Ventilasi',
        'Layar Plafon Entertainment 21.4 Inci Cinema Display dengan Remote',
        'Kulkas Cerdas Smart Refrigerator (Dapat diatur Dingin & Hangat 0°C - 50°C)',
        'Suspensi Udara Dual-Chamber dengan CDC Active Damping',
        'Platform 800V Silicon Carbide XPower Ultra Fast Charge',
      ],
      description: 'XPENG X9 adalah mahakarya MPV keluarga dan eksekutif kelas atas dengan ruang interior terluas di kelasnya, kelincahan luar biasa berkat Rear-Wheel Steering, dan kemewahan setara first-class penerbangan.',
      isFeatured: true,
      isHot: true,
      isNew: true,
      inStock: true,
    },
    {
      id: 'model-g9',
      slug: 'xpeng-g9',
      name: 'XPENG G9',
      tagline: 'Flagship Luxury Intelligent 5-Seater SUV',
      category: 'SUV',
      startingPrice: 1050000000,
      formattedPrice: 'Rp 1.050.000.000',
      rangeKm: '650 KM (CLTC)',
      acceleration0to100: '3.9 Detik',
      maxPower: '551 HP / 717 Nm',
      batteryCapacity: '98 kWh 800V High Energy Battery',
      fastChargeTime: '10-80% dalam 15 menit',
      driveType: 'RWD / Performance AWD',
      heroImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85',
      sideImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=85',
      interiorImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85',
      gallery: [
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85',
        'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85',
      ],
      colors: [
        { name: 'Kaitoke Green', hex: '#1b4332' },
        { name: 'Aero White', hex: '#f8fafc' },
        { name: 'Space Black', hex: '#111827' },
        { name: 'Stardust Silver', hex: '#94a3b8' },
      ],
      variants: [
        {
          name: 'G9 570 Pro RWD',
          price: 1050000000,
          formattedPrice: 'Rp 1.050.000.000',
          range: '570 km',
          acceleration: '6.4 detik',
          drivetrain: 'RWD 313 HP',
          battery: '78.2 kWh LFP',
        },
        {
          name: 'G9 650 Performance AWD Max',
          price: 1220000000,
          formattedPrice: 'Rp 1.220.000.000',
          range: '650 km',
          acceleration: '3.9 detik',
          drivetrain: 'AWD 551 HP',
          battery: '98 kWh NMC',
        },
      ],
      highlights: [
        'Audio Dynaudio Confidence 28 Speaker dengan 7.1.4 Dolby Atmos 5D Cinema',
        'Dual 14.96-inch 2K High Resolution Display untuk Driver & Passenger',
        'Suspensi Udara Dual-Chamber dengan Auto-Leveling',
        'Kursi Kulit Nappa Premium dengan Heating, Cooling & Massage',
        'Fitur V2L (Vehicle to Load) 3.3 kW untuk peralatan elektronik outdoor',
      ],
      description: 'XPENG G9 menyatukan performa supercar, kenyamanan suspensi udara kelas flagship, dan teknologi multimedia termutakhir di segmen luxury SUV.',
      isFeatured: true,
      inStock: true,
    },
    {
      id: 'model-p7i',
      slug: 'xpeng-p7i',
      name: 'XPENG P7i',
      tagline: 'Sports Smart Electric Sedan - Wing Edition Available',
      category: 'Sedan',
      startingPrice: 780000000,
      formattedPrice: 'Rp 780.000.000',
      rangeKm: '702 KM (CLTC)',
      acceleration0to100: '3.9 Detik',
      maxPower: '473 HP / 757 Nm',
      batteryCapacity: '86.2 kWh High-Density NMC',
      fastChargeTime: '10-80% dalam 20 menit',
      driveType: 'RWD / AWD Performance',
      heroImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85',
      sideImage: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=85',
      interiorImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85',
      gallery: [
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85',
        'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=85',
      ],
      colors: [
        { name: 'Super Green', hex: '#10b981' },
        { name: 'Kaitoke Gray', hex: '#475569' },
        { name: 'Ice White', hex: '#f8fafc' },
        { name: 'Star Silver', hex: '#cbd5e1' },
      ],
      variants: [
        {
          name: 'P7i 702 Pro RWD',
          price: 780000000,
          formattedPrice: 'Rp 780.000.000',
          range: '702 km',
          acceleration: '6.4 detik',
          drivetrain: 'RWD 276 HP',
          battery: '86.2 kWh',
        },
        {
          name: 'P7i 610 Max Wing Edition (Pintu Gunting Scissor)',
          price: 920000000,
          formattedPrice: 'Rp 920.000.000',
          range: '610 km',
          acceleration: '3.9 detik',
          drivetrain: 'Dual Motor AWD 473 HP',
          battery: '86.2 kWh',
        },
      ],
      highlights: [
        'Desain Aerodinamis Cd 0.236 dengan Electric Rear Spoiler',
        'Tersedia Opsi Scissor Wing Doors elektrik dengan sensor anti-bentur',
        'Brembo 4-Piston Braking System (Jarak Pengereman 33.3m)',
        'Xsmart OS dengan Snapdragon 8155 & Surround Sound System',
      ],
      description: 'Sedan sport listrik ikonik dengan handling presisi, akselerasi kilat, dan opsi pintu gunting Wing Edition yang spektakuler.',
      isFeatured: false,
      inStock: true,
    },
    {
      id: 'model-mona-m03',
      slug: 'xpeng-mona-m03',
      name: 'XPENG MONA M03',
      tagline: 'Intelligent AI Sedan for Modern Urbanites',
      category: 'Sedan',
      startingPrice: 480000000,
      formattedPrice: 'Rp 480.000.000',
      rangeKm: '620 KM (CLTC)',
      acceleration0to100: '7.4 Detik',
      maxPower: '218 HP',
      batteryCapacity: '62.2 kWh Blade LFP',
      fastChargeTime: '30-80% dalam 26 menit',
      driveType: 'FWD',
      heroImage: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=85',
      sideImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85',
      interiorImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85',
      gallery: [
        'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=85',
      ],
      colors: [
        { name: 'Nebula Cyan', hex: '#06b6d4' },
        { name: 'Pearl White', hex: '#ffffff' },
        { name: 'Graphite Grey', hex: '#374151' },
      ],
      variants: [
        {
          name: 'MONA M03 515 Plus',
          price: 480000000,
          formattedPrice: 'Rp 480.000.000',
          range: '515 km',
          acceleration: '7.8 detik',
          drivetrain: 'FWD 190 HP',
          battery: '51.8 kWh LFP',
        },
        {
          name: 'MONA M03 620 Max Smart',
          price: 540000000,
          formattedPrice: 'Rp 540.000.000',
          range: '620 km',
          acceleration: '7.4 detik',
          drivetrain: 'FWD 218 HP',
          battery: '62.2 kWh LFP',
        },
      ],
      highlights: [
        'Koefisien Hambatan Terendah di Dunia Cd 0.194',
        'Bagasi Liftback Ekstra Luas 621 Liter',
        'Layar Sentuh 15.6 Inci dengan Navigasi 3D Real-time',
        'Sistem Audio Panorama 18-Speaker dengan Headrest Speaker',
      ],
      description: 'Sedan listrik berteknologi tinggi dengan harga terjangkau, efisiensi energi terbaik di kelasnya, dan desain liftback serbaguna.',
      isFeatured: false,
      isNew: true,
      inStock: true,
    },
  ],

  promotions: [
    {
      id: 'promo-1',
      slug: 'special-promo-bulan-ini-xpeng-g6-x9',
      title: 'Promo Spesial Bulan Ini: Free Wallbox 7kW + Bunga 0% s/d 2 Tahun',
      badge: 'PROMO BULAN INI',
      period: 'Berlaku s/d Akhir Bulan Ini',
      excerpt: 'Dapatkan paket bundling eksklusif setiap pemesanan XPENG G6 dan X9: Free Home Charger 7kW, Free Asuransi 1 Tahun, dan Subsidi Trade-In hingga Rp 25 Juta!',
      content: `Kabar gembira untuk Anda yang ingin beralih ke mobil listrik pintar XPENG! Di promo spesial bulan ini, kami menghadirkan paket penawaran terbaik:

1. **Free Official XPENG Wallbox Charger 7kW** senilai Rp 18.000.000 (Termasuk jasa instalasi dan kabel hingga 10 meter).
2. **Program Bunga 0%** dengan tenor hingga 2 tahun melalui partner leasing resmi (Maybank, Mandiri Tunas Finance, BCA Finance, CIMB Niaga Auto Finance).
3. **Subsidi Trade-In (Tukar Tambah)** hingga Rp 25.000.000 untuk semua merk mobil bensin/hybrid lama Anda.
4. **Garansi Baterai Seumur Hidup / 8 Tahun 160.000 KM** + Free Jasa & Spareparts Service Berkala 5 Tahun / 100.000 KM.
5. **Kaca Film Solar Gard / V-Kool Premium** Full Body + Karpet Original XPENG.

*Unit ready stock dengan pilihan warna favorit. Proses SPK cepat, data kredit dibantu hingga 100% APPROVE.*`,
      bannerImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=85',
      validUntil: '31 Maret 2025',
      terms: [
        'Berlaku untuk pemesanan (SPK) selama periode promo',
        'Promo Bunga 0% mengikuti syarat & ketentuan leasing yang berlaku',
        'Instalasi Wallbox gratis mencakup wilayah Jabodetabek, Surabaya, Bandung, dan Bali',
        'Subsidi trade-in berlaku setelah appraisal unit mobil lama oleh tim resmi',
      ],
      isFeatured: true,
      publishDate: '2025-02-01',
      category: 'Special Promo',
    },
    {
      id: 'promo-2',
      slug: 'program-dp-ringan-angsuran-terjangkau',
      title: 'Paket DP Ringan Mulai 10% & Angsuran Ringan XPENG G6',
      badge: 'DP RINGAN',
      period: 'Flash Promo Mingguan',
      excerpt: 'Miliki XPENG G6 dengan DP mulai dari Rp 69 Jutaan atau angsuran mulai Rp 11 Jutaan per bulan. Proses 1 hari kerja langsung approval.',
      content: `Ingin memiliki XPENG G6 tanpa mengganggu cash flow bisnis dan keluarga Anda? Kami menyediakan paket pembiayaan fleksibel:

- **Paket DP Ringan:** Mulai dari 10% (DP Rp 69 Jutaan)
- **Paket Angsuran Ringan:** Mulai Rp 11.500.000 / bulan dengan tenor s/d 6 tahun
- **Paket Balloon Payment:** Bayar 50% di akhir tenor dengan cicilan bulanan super hemat
- **Bebas Ganjil Genap Jakarta** + Biaya Pajak Tahunan (PKB) sangat murah hanya ~Rp 1 Jutaan / tahun!

Hubungi Pak Hendra sekarang untuk mendapatkan hitungan simulasi kredit yang disesuaikan dengan budget Anda.`,
      bannerImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85',
      validUntil: '15 Maret 2025',
      terms: [
        'Berlaku untuk KTP Jabodetabek dan seluruh Indonesia',
        'Data dijemput ke rumah/kantor atau via WhatsApp',
        'Khusus wiraswasta / profesional / karyawan tetap',
      ],
      isFeatured: true,
      publishDate: '2025-02-10',
      category: 'Low DP & Interest',
    },
    {
      id: 'promo-3',
      slug: 'vip-experience-xpeng-x9-luxury-mpv',
      title: 'Exclusive VIP Test Drive & Priority Allocation XPENG X9 MPV',
      badge: 'VIP PROMO',
      period: 'Limited 20 Units',
      excerpt: 'Dapatkan antrean unit prioritas dan gratis Portable Charger + Aksesoris VIP XPENG X9 senilai Rp 15 Juta.',
      content: `Bagi Anda yang mendambakan kenyamanan MPV listrik termewah untuk keluarga atau kebutuhan VIP Direksi, nikmati program eksklusif XPENG X9:

- **Home Test Drive VIP:** Mobil test drive diantar langsung ke rumah atau kantor Anda dengan briefing fitur lengkap oleh Product Specialist.
- **Priority Unit Delivery:** Alokasi unit pertama langsung kirim ke garasi Anda tanpa menunggu lama.
- **Free XPENG Portable Charger 3.5 kW** + Adaptor Fast Charging.
- **Voucher Coating Keramik Premium** senilai Rp 7.500.000.`,
      bannerImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=85',
      validUntil: '31 Maret 2025',
      terms: [
        'Terbatas untuk 20 pembeli pertama bulan ini',
        'Jadwal Test Drive VIP harus reservasi minimal H-1',
      ],
      isFeatured: false,
      publishDate: '2025-02-15',
      category: 'Special Promo',
    },
  ],

  testimonials: [
    {
      id: 'testi-1',
      customerName: 'Bpk. David & Ibu Natalia',
      location: 'Pantai Indah Kapuk (PIK), Jakarta Utara',
      carModel: 'XPENG G6 Long Range - Arctic White',
      deliveryDate: '18 Februari 2025',
      rating: 5,
      quote: 'Pelayanan Pak Hendra luar biasa profesional dan responsif! Mulai dari awal minta test drive ke rumah di PIK, simulasi kredit yang transparan, sampai serah terima unit di dealer tepat waktu. Wall charger juga langsung dipasang besoknya oleh tim teknisi resmi. Mobilnya hening, akselerasinya luar biasa!',
      photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80',
      verifiedPurchase: true,
      salesConsultant: 'Hendra Gunawan',
    },
    {
      id: 'testi-2',
      customerName: 'Bpk. Hendry Kurniawan (CEO Tech Logistics)',
      location: 'Pondok Indah, Jakarta Selatan',
      carModel: 'XPENG X9 7-Seater AWD - Dark Knight',
      deliveryDate: '12 Februari 2025',
      rating: 5,
      quote: 'XPENG X9 benar-benar mengubah standar MPV mewah. Anak-anak suka sekali layar bioskop plafon dan kursi zero gravity-nya. Pak Hendra sangat paham detail teknologi mobil ini dan mengurus semua surat-surat STNK/Plat nomor dengan cepat. Highly recommended!',
      photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      verifiedPurchase: true,
      salesConsultant: 'Hendra Gunawan',
    },
    {
      id: 'testi-3',
      customerName: 'Bpk. Anthony Wijaya & Rekan',
      location: 'Kelapa Gading, Jakarta Utara',
      carModel: 'XPENG G9 Flagship AWD - Kaitoke Green',
      deliveryDate: '04 Februari 2025',
      rating: 5,
      quote: 'Trade-in mobil lama saya dihargai sangat wajar dan prosesnya sangat dibantu. Suspensi udara G9 empuk sekali di jalan tol Jakarta-Bandung dan sound system Dynaudio 28 speakernya bikin betah macet-macetan. Terima kasih Pak Hendra atas hadiah promo wall chargernya!',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      verifiedPurchase: true,
      salesConsultant: 'Hendra Gunawan',
    },
    {
      id: 'testi-4',
      customerName: 'Ibu Felicia Tan',
      location: 'Gading Serpong, Tangerang',
      carModel: 'XPENG G6 Performance AWD - Photon Orange',
      deliveryDate: '26 Januari 2025',
      rating: 5,
      quote: 'Suka banget warna Photon Orange-nya yang eye-catching! Pak Hendra kasih diskon promo dan bonus kaca film premium terbaik. Pengisian daya 800V-nya super cepat cuma colok 15 menit pas mampir ngopi di rest area.',
      photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
      verifiedPurchase: true,
      salesConsultant: 'Hendra Gunawan',
    },
  ],

  usps: [
    {
      id: 'usp-1',
      icon: 'ShieldCheck',
      title: 'Authorized Official Dealer',
      desc: 'Jaminan unit 100% baru, garansi baterai resmi 8 Tahun / 160.000 KM, dan dukungan teknisi tersertifikasi XPENG Global.',
    },
    {
      id: 'usp-2',
      icon: 'Zap',
      title: 'Free Wallbox Charger 7kW',
      desc: 'Setiap pembelian unit mendapatkan bonus Wallbox Home Charger resmi beserta instalasi gratis langsung di rumah Anda.',
    },
    {
      id: 'usp-3',
      icon: 'Car',
      title: 'Free Home Test Drive',
      desc: 'Jadwalkan test drive langsung ke rumah atau kantor Anda. Rasakan kecanggihan berkendara XPENG tanpa repot datang ke showroom.',
    },
    {
      id: 'usp-4',
      icon: 'Percent',
      title: 'Bunga 0% & DP Ringan 10%',
      desc: 'Bekerja sama dengan bank & leasing terkemuka untuk proses persetujuan kredit tercepat dan angsuran paling hemat.',
    },
    {
      id: 'usp-5',
      icon: 'RefreshCw',
      title: 'Terima Trade-In Semua Merk',
      desc: 'Tukar mobil lama Anda (Bensin/Hybrid/EV) dengan penawaran harga terbaik dan subsidi tukar tambah hingga puluhan juta rupiah.',
    },
    {
      id: 'usp-6',
      icon: 'Sparkles',
      title: 'Pelayanan VIP 24/7',
      desc: 'Konsultasi cepat via WhatsApp, pengurusan plat nomor resmi, asuransi, hingga pengiriman towing VIP berhias pita ke depan garasi Anda.',
    },
  ],

  leads: [
    {
      id: 'lead-1',
      customerName: 'Robert Setiawan',
      phone: '081311223344',
      city: 'Jakarta Barat',
      selectedModel: 'XPENG G6 Long Range',
      inquiryType: 'Test Drive',
      preferredDate: '2025-03-02',
      notes: 'Ingin test drive ke rumah di Puri Indah hari Sabtu pagi',
      status: 'New',
      createdAt: '2025-02-27 10:30',
    },
    {
      id: 'lead-2',
      customerName: 'Susanto Lim',
      phone: '081299887766',
      city: 'Tangerang',
      selectedModel: 'XPENG X9 702 Max',
      inquiryType: 'Credit Simulation',
      notes: 'Minta hitungan DP 20% tenor 3 tahun dan 4 tahun',
      status: 'Followed Up',
      createdAt: '2025-02-26 14:15',
    },
  ],

  lastUpdated: new Date().toISOString(),
};
